### ISSUE TITLE
viページに対する正誤

### ISSUE THREAD

**Issue by k16shikano** [LambdaNote/polished-ruby-ja-feedbacks-beta2#318]

**Comment by yahonda** [comment]
> インテリジェントキャッシングやマテリアライズド ビューを利用して問題を回避できることもありますが、

マテリアライズドビューはPostgreSQLの機能名ですが、インテリジェントキャッシングは機能名ではありません。原文にもデータベース以外でintelligent cachingという語句を使って記述している部分があり、そこでは"気の利いたキャッシュ"と訳出しているみたいです。

日本語版p84

> ローカル変数やインスタンス変 数を気のきいたキャッシュとして使うことで、

原文
> You also learned how both local variables and instance variables can provide substantial performance benefits with intelligent caching.

### 翻訳案

PostgreSQLにはバッファキャッシュもあるし[クエリーキャッシュ](https://www.postgresql.org/about/news/postgresql-query-cache-released-1296/)もあって性能の向上に寄与しているので、「データベースのキャッシュ機能やマテリアライズ...」とかでもいいと思います。3章と同じような「気の利いたキャッシュ」はここではあんまりピンときませんでした。

https://www.postgresql.org/about/news/postgresql-query-cache-released-1296/

**Comment by yahonda** [comment]
> マテリアライズドビューはPostgreSQLの機能名ですが、インテリジェントキャッシングは機能名ではありません。

これは、マテリアライズドビューはPostgreSQLの機能名ですが、インテリジェントキャッシングは機能名ではありませんが、カタカナで2つ並ぶと同じ種類の名詞が並んでいるので、機能のように思われるという意図です。

**Comment by yahonda** [comment]
同じページでもう一つ:

> それぞれのカラムには、他のカラムに格納されている値とは異なる値を格納する
(たとえば、artist_name_1、artist_name_2 といったカラムは使わない)

これは第一正規化しましょうの具体例説明していると思いました。
が、「他のカラムに格納されている値とは異なる値」の「値」があんまりすっきりしません。

というのは、ここで使わないようにガイドされている、artist_name_1とartist_name_2 という列があったとして、
そこに入る値は、例えばartist_name_1にモーツァルトとartist_name_2にベートーベンを入れたら、「異なる値」が格納されてます。

が、ここで言いたいのは、artist_nameのような列が同じ行で繰り返し発生したら、それは同じ列の複数のレコードに分けましょうということになるので、適切な訳は少なくとも具体的な値を想定するものではなく、値の種類を指す何かの方がいいように思います。

**Comment by kakutani** [comment]
> 「データベースのキャッシュ機能やマテリアライズ...」とかでもいいと思います

ありがとうございます。原文の意図としてはこれぐらいでも良さそうですね。参考になります!

> が、「他のカラムに格納されている値とは異なる値」の「値」があんまりすっきりしません。

こちらのフィードバックもありがとうございます。確かに「異なる値」だと説明がちょっと妙ですね…と思って原文を見たら「different data」でした(なるほど)。これを「データ」にしても問題は解決しないので、ちょっと補ってあげる必要がありそうですね。「異なる種類のデータ」みたいな感じかな…。

**Comment by kakutani** [comment]
β3で「データベースのキャッシュ機能やマテリアライズドビューを利用して問題を回避できることもありますが、」として修正しました。
