### ISSUE TITLE
viiページに対する正誤

### ISSUE THREAD

**Issue by k16shikano** [LambdaNote/polished-ruby-ja-feedbacks-beta2#319]

**Comment by yahonda** [comment]
> 非正規化の例を見てみましょう。いま、3 つのテーブルがあるとします。1 つめは
楽曲の情報を格納したtracks、2つめはアーティストの情報を格納したartists、3 つめはそれらの結合テーブル artists_tracks とします。結合テーブルには tracks テーブルと artists テーブルに対する外部キー制約が適用されています。曲情報と アーティスト情報を取得するには、以下のいずれかが必要です。

「楽曲の情報を格納したtracks」と言っているので、「曲情報と アーティスト情報」も「楽曲情報と アーティスト情報」のように楽曲で統一した方がいいかと思います。

**Comment by yahonda** [comment]
> 「関連するアーティスト情報と一緒に曲情報を取 得する場合」

ここの「曲情報」も「楽曲情報」で統一した方がいいかと思います。

**Comment by yahonda** [comment]
時間経って思い直してみると、曲なのか楽曲なのかは重箱の隅をつつくようなレビューだったと思いますので、訳者の判断に委ねたいと思います。

**Comment by kakutani** [comment]
フィードバックありがとうございます。「楽曲」と「曲」の両方使っていて特にこだわりがあるわけではないので、どうしよっかなというのは編集とも相談します!

**Comment by kakutani** [comment]
編集と相談して、β3では:

> 非正規化の例を見てみましょう。いま、3つのテーブルがあるとします。1つめは曲名などの情報を格納した<code>tracks</code>、

とここだけ「曲名など」として「曲情報」という言葉を本文で使わないようにしてみました。
